on: push

jobs:
  npm-build:
        runs-on: ubantu-latest
        steps:
        - run: pwd
        - run: npm --version
        - uses: actions/checkout@v4
        - run: npm install
        - run: npm run build

