name: Deploy to Vercel

on: 
  push:
    branches:
      - feature-dev-drizzle


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel  
        uses: amondnet/vercel-action@v25  # 使用 Vercel GitHub Action  
        with:  
          vercel-token: ${{ secrets.VERCEL_TOKEN }}        # Vercel API 令牌  
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 

