name: Deploy to Vercel

on: 
  push:
    branches:
      - feature-dev-drizzle


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to Vercel  
        uses: amondnet/vercel-action@v20.1.0  # 使用 Vercel GitHub Action  
        with:  
          vercel-token: ${{ secrets.VERCEL_TOKEN }}        # Vercel API 令牌  
          vercel-organization-id: ${{ secrets.VERCEL_ORG_ID }}  # Vercel 组织 ID  
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}    # Vercel 项目 ID  
          vercel-args: '--prod'  # 加 --prod 进行生产部署，若需要可以删除  
        env:  
          VERCEL_GITHUB_COMMIT_SHA: ${{ github.sha }}  # 用于设置当前的 Git 提交  

